consumerKey : <enter the consumer-key of your app>
consumerSecret : <enter the consumer-secret of your app>
accessToken : <enter the access-token of your app>
accessTokenSecret : <enter the access-token-secret of your app>
